/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.leca.avro;
@org.apache.avro.specific.AvroGenerated
public enum EventTypeMatch implements org.apache.avro.generic.GenericEnumSymbol<EventTypeMatch> {
  match  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"EventTypeMatch\",\"namespace\":\"com.leca.avro\",\"symbols\":[\"match\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
