/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.leca.avro;
@org.apache.avro.specific.AvroGenerated
public enum EventTypeInAppPurchase implements org.apache.avro.generic.GenericEnumSymbol<EventTypeInAppPurchase> {
  in_app_purchase  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"EventTypeInAppPurchase\",\"namespace\":\"com.leca.avro\",\"symbols\":[\"in_app_purchase\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
